<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_MEMBER LOGIN_view3</name>
   <tag></tag>
   <elementGuidId>e7f0db83-28e7-49e4-b0b6-63809ba2935d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='view3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>12b3052d-0e4a-4bff-a80b-16e89114391c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye-slash fa-2x</value>
      <webElementGuid>b7a1d39a-caa5-4853-be8f-dca3ec7f77ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view3</value>
      <webElementGuid>205e7b81-ce70-43dc-a3c1-ec2abac5959a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view3&quot;)</value>
      <webElementGuid>d3487611-742e-4864-82b0-7fa56f71655c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='view3']</value>
      <webElementGuid>91db931d-16e1-4557-9498-6615277cc17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Icon']/a/i</value>
      <webElementGuid>0178787d-6697-4c84-86ba-5e3a829197fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>a11a8404-a402-45d3-bc78-2687640299da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'view3']</value>
      <webElementGuid>1061a49e-dbc2-468b-a833-e01897049c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
